config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "floating#index"
  get 'floating/modal'
  get 'floating/stacking_context'
  get 'floating/dropdown_content'
  get 'floating/window_overflow'
  get 'floating/system_tests'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/floating_controller.rb
class FloatingController < ApplicationController

  def index
    @debug_log = params[:console_debug_log] == "true" ? true : false
  end

  def modal

  end

  def dropdown_content
    sleep 0.5
    render layout: false
  end

  def stacking_context

  end

  def window_overflow

  end

  def system_tests

  end
end

app/helpers/dropdown_helper.rb
module DropdownHelper

  #== dropdown helper
  # @param [button_content] Proc or String for content of the button element
  # @param [panel_at_place] true (default: false) => it would render the panel into content_for(:dropdown_panels) on sticky parts (left-menu / top-bar) panels should be at place for avoiding that the panel would scroll with the content
  # @block [panel_content] Panel Content as block
  # what it does:
  # a) wraps the button_content in element like: %button{ data: { controller: 'dropdown', ... } } and renders it at place
  # b) wraps the panel_content in a corresponding element and renders it to the dropdown_panels-box (because of z-index-hierarchy)
  # c) the stimulus controller always adds the class .floating-dropdown-panel to the panel
  def dropdown(button_content, title = false, options = {}, &panel_content)

    if title.is_a?(Hash)
      options = title.dup
      title = false
    end

    panel_at_place = options.delete(:panel_at_place) || false
    placement = options.delete(:placement) || :bottom

    id = if options.key?(:id)
           raise ":id option is not allowed. Use :button_id and/or :panel_id"
         elsif options.key?(:panel_id)
           options.delete(:panel_id)
         else
           "dropdown-panel-#{SecureRandom.hex(4)}"
         end

    button_id = options.delete(:button_id)

    src = options.delete(:src)

    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # create the Button
    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    button_options = options.dup
    button_options[:class] = [options[:class], 'dropdown-button'].compact.join(' ')
    button_options = button_options.merge(data: { controller: 'csedl-dropdown', toggle: id })

    r = content_tag(:button, button_options.merge(id: button_id)) do
      if button_content.is_a?(Proc)
        capture(&button_content)
      elsif button_content.is_a?(Symbol) || button_content.is_a?(String)
        button_content
      end
    end

    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # create the panel
    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    panel_options = options.dup
    panel_options[:class] = [options[:class], 'dropdown-panel hide'].compact.join(' ')
    panel_options[:id] = id
    panel_options[:placement] = placement
    panel_options['data-src'] = src if src

    panel = content_tag(:div, panel_options) do
      r2 = content_tag :div, class: 'header' do
        r3 = content_tag :div, class: 'title' do
          title
        end
        r3 << content_tag(:span, class: 'close-panel-button') {'X'}
      end
      r2 << content_tag(:div, class: 'panel-content') do
        capture(&panel_content) if block_given?
      end
      r2 << content_tag(:div, id: 'arrow') do
        nil
      end
    end

    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # return the result
    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    if panel_at_place
      r << panel
    else
      r << content_for(:dropdown_panels) do
        panel
      end
    end

  end

end

app/helpers/tooltip_helper.rb
module TooltipHelper

  def tooltip(label, options = {}, &content)

    panel_at_place = options.delete(:panel_at_place) || false
    delay = options.delete(:delay) || 0.1
    src = options.delete(:src)

    id = ['tooltip', SecureRandom.hex(4)].join('-')

    lab = if label.is_a?(Proc)
            capture &label
          else
            label
          end
    cont = capture(&content) if block_given?

    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # create the Label
    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    label_options = options.dup
    label_options[:class] = [options[:class], 'tooltip-label'].compact.join(' ')
    label_options = label_options.merge(data: { controller: 'csedl-tooltip', toggle: id, delay: delay })

    label_element = if block_given? && cont.present?
                      content_tag(:span, label_options) do
                        lab
                      end
                    else
                      lab
                    end

    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # create the panel
    # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    panel_options = options.dup
    panel_options[:class] = [options[:class], 'tooltip-panel hide'].compact.join(' ')
    panel_options[:id] = id
    panel_options['data-src'] = src if src

    panel_element = if block_given? && cont.present?
                      content_tag(:div, panel_options) do
                        r2 = content_tag :div, id: 'arrow' do
                          ; nil;
                        end
                        r2 << content_tag(:div, class: 'tooltip-content') do
                          cont
                        end
                      end
                    end

    if !panel_element
      label_element
    elsif panel_at_place
      r = label_element
      r << panel_element
    else
      content_for(:dropdown_panels) do
        panel_element
      end
      label_element
    end

  end
end

app/views/floating/dropdown_content.haml
%h2 Server Response (delayed):
- rand(1..6).times do
  %h3
    =  SecureRandom.hex(rand(2..8))

app/views/floating/index.haml
#scroller{ data: { controller: 'csedl-place-dropdown-panels', on: 'scroll resize-observer', run_after: 500 } }
  #viewport
    = dropdown('panel-at-place', panel_at_place: true, class: 'dropdown-2') do
      'content'
    %br
    = dropdown('panel-on-root', class: 'dropdown-1') do
      'content'

%p.text-grey
  This box is relative to the window height/width and with delay (transition/css)

%h3
  Fetch content from server (delayed) on opening
  = dropdown('btn', src: floating_dropdown_content_path) do
    'content'


%h3 Custom Events on opening and closing
= dropdown('btn', panel_id: 'panel3', button_id: 'button3') do
  'content'


%h3 Nested dropdowns
= dropdown('nest', placement: 'right-start') do
  .text-red
    Here are some bugs to fix: closing and arrow behaviour for nested dropdowns
  = dropdown('nest2', panel_at_place: true, placement: 'right-start') do
    = dropdown('nest3', panel_at_place: true, placement: 'right-start')


%h3 Tooltip
%p
  This is a
  = tooltip('tooltip') do
    tooltip-content
  = ' and this is a'
  = tooltip('tooltip with content from server', src: floating_dropdown_content_path) do
    tooltip-content
  = ' and with a long hover-delay'
  = tooltip('tooltip with content from server', src: floating_dropdown_content_path, delay: 0.8) do
    tooltip-content

app/views/floating/modal.haml
#modal-page
  %h1 modal

app/views/floating/stacking_context.haml
%h1
  Stacking context

#stacking-context-page
  #z1
    z-1
  #z2
    z-2
    #z2-child
      %span{data: {tooltip: true, click_open: 'true'}, tabindex: "1", title: "Fancy word for a beetle."}
        tooltip
      z-2-child
  #z3
    z-3

app/views/floating/system_tests.haml
%br

#drop-btn.dropdown-button{ data: {controller: 'dropdown', toggle: 'panel'} }
  drop
#panel.hide
  .close-panel-button
    close

app/views/floating/window_overflow.haml
#overflowing-wrapper
  This div overflows the screen size

  - 20.times do |no|
    %li= no

  %button.dropdown-button#constrain-btn{ data: { controller: 'dropdown', toggle: 'overflowing-panel', panel_class: 'panel-4', constrain_to_window_borders: 'true' } }
    button => constrain_to_window_borders: true
  #overflowing-panel.hide
    - 20.times do |no|
      %li= no

  %button.dropdown-button{ data: { controller: 'dropdown', toggle: 'overflowing-panel', panel_class: 'panel-4' } }
    button => constrain_to_window_borders: false (default)
  #overflowing-panel.hide
    - 20.times do |no|
      %li= no


  %ul
    - 100.times do |no|
      %li= no

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Stimulus Dropdown
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    %meta{ name: "stimulus-dropdown", content: "console-debug-log=#{@debug_log ? 'true' : 'false'}; close-panel-selector=.close-panel-button;" }/
    %meta{ name: "stimulus-dropdown", content: "dropdown-content-wrapper-selector=.panel-content;" }/
    %meta{ name: "stimulus-dropdown", content: "tooltip-content-wrapper-selector=.tooltip-content;" }/

    = csrf_meta_tags
    = csp_meta_tag

    =# stylesheet_link_tag "application", "data-turbo-track": "reload"
    = vite_stylesheet_tag 'application.scss', media: :all
    = javascript_importmap_tags
    = vite_client_tag
    = vite_javascript_tag 'application'
    /

  %body{ id: "#{action_name}-body".gsub('_','-') }

    %h2
      Rails Dropdown based on Stimulus and Floating-ui

    %p.page-head
      = link_to 'Stylesheets', 'https://gitlab.com/sedl/stimulusfloatingdropdown/-/tree/main/app/frontend/stylesheets?ref_type=heads'
      = ' | '
      = link_to 'View', 'https://gitlab.com/sedl/stimulusfloatingdropdown/-/blob/main/app/views/floating/index.haml?ref_type=heads'
      = ' | '
      = link_to 'Helpers', 'https://gitlab.com/sedl/stimulusfloatingdropdown/-/tree/main/app/helpers?ref_type=heads'
      = ' | '
      = link_to 'JS', 'https://gitlab.com/sedl/stimulusfloatingdropdown/-/tree/main/app/frontend/javascript?ref_type=heads'


      %span.float-right
        = link_to 'NPM', 'https://www.npmjs.com/package/@csedl/stimulus_dropdown'
        = ' | '
        = link_to 'GitLab', 'https://gitlab.com/sedl/stimulusfloatingdropdown'
        = ' | '
        = link_to 'floating-UI', 'https://floating-ui.com/'
        - if Rails.env.development?
          = ' | '
          = link_to 'Demo', 'http://stimulus-dropdown.sedlmair.ch'

    %span
      = "Console debug-log is"
      %strong
        = "#{@debug_log ? 'on' : 'off'}."
      Turn it
      = link_to "#{@debug_log ? 'off' : 'on'}", root_path(console_debug_log: (@debug_log ? 'false' : 'true'))
    = yield
    = yield :dropdown_panels